install/ci-linux/ci/runCI
mod_ci/controllers.py
templates/test/by_id.html

Storing stderr during ./build in logfile.
Changed field from html to file to enable uploading of logfile in case
of build failure.
Sending logfile to server using type 'logupload'.
Storing file in LogFiles folder in format test_id.txt e.g 183.txt.

Logging build errors and displaying log file.

---

install/install.sh
mod_test/models.py

Adds  timezones to timestamps. 
Previous timestamps :
> 2016-12-16 19:26:44
Now (almost similar)  :
> 2016-12-16 19:26:44 (UTC)

Display Timezone in Sample Platform.

---

templates/regression/index.html

Added multi-category support

---

mod_ci/controllers.py
mod_regression/models.py
mod_sample/controllers.py
mod_test/controllers.py
mod_test/models.py

Didn't look like the models needed to be changed.

Accounted for non-zero exit_code

---

mod_test/nicediff/diff.py

**Changes**
> Completely changed compress function, the old one was buggy ( Details : https://github.com/canihavesomecoffee/sample-platform/issues/27).
> Only display those lines which have some difference in them (Details : https://github.com/canihavesomecoffee/sample-platform/issues/13).
> Also displays those lines which are extra in one file but absent in another. Needed to display correct differences.
For two files
```
00:01:24,867 --> 00:01:27,931
These are the codes for the signal.
Good luck.
24
00:01:27,932 --> 00:01:31,806
Why four days? A kill list was
intercepted from Skynet
I love .. Saurabh
Apple
```
and
```
00:01:31,520 --> 00:01:35,394
These are the codes for the signal.
Good luck.
24
00:01:35,395 --> 00:01:39,593
Why four days tomato A tomato kill list was
intercepted from …
```

Improvements to the diff generator

---

install/install.sh

MySQL Warning removed : leads easily login into mysql without any issues

Install file fixes: MySQL Warning removed

---

templates/test/by_id.html

Fix the result status of individual tests.

---

static/css/app.css

Improve responsiveness of platform

---

mailer.py

This is my first time contributing to this project. Constructive criticism is definitely welcome. 
#21

Documented mailer.py

---

templates/regression/index.html

dropdown style fixed

---

static/css/app.css

#53 fixed
working for all device width

Test Progress bar issue fixed

---

mod_auth/models.py

Documentation for mod_auth/models.py

added documentation for mod_auth/models.py

---

mod_auth/forms.py

Documentation for mod_auth/forms.py

Documentation for mod_auth/forms.py

---

README.md

---
Added documentation for support of installing sample platform on windows
Used Cygwin for windows support of installing sample platform

[IMPROVEMENT] Added windows doc

---

mod_ci/controllers.py

FIX buges in waiting time pr
---
Fixed negative time issue pr2>pr1 and list out of index

time conflict and list out of index in waiting time pr [FIX]

---

mod_ci/controllers.py

---
Fixes for TypeError: object of type 'Alias' has no len()

[FIX] some fixes in waiting time feature

---

mod_ci/controllers.py

---
Code helps in testing changes with last commit or in case if file/ output missing, it tests with the last version test file. Fixes #31.

[FIX] added master sync to last commit 

---

mod_ci/controllers.py

---
Issue : can't subtract offset-naive and offset-aware datetimes

[FIX] some fixes in time pr

---

mod_test/controllers.py
templates/test/by_id.html

---
Implements the functionality to poll for test progress with javascript. Closes #70.

[FEATURE] added ajax call to retrieve data for test progress

---

mod_ci/controllers.py

---
added support for both testing in both linux and windows in parallel

[FIX] added windows dual support

---

templates/test/by_id.html

[FIX] some fix in ajax pr

---

install/install.sh
install/installation.md
mod_upload/controllers.py
mod_upload/progress_ftp_upload.py

[FEATURE] Please prefix your pull request with one of the following: **[FEATURE]** **[FIX]** **[IMPROVEMENT]**.
---
Follow the steps in the installation guide.
progress_ftp_upload.py needs to be uploaded that will run at the server end that will add the sample to database and upload the sample to the queued samples in /repository if no same sample exist
if any issue arises, compare it with test server otherwise ping me.

[FEATURE] FTP upload support

---

mod_ci/controllers.py

#86 
---
making 2 entries in GeneralData:
a) last_commit: This is the last commit done on the repo.
b) previous_commit: This is the commit before the last commit on the repo.

[FIX] fixed self commit check

---

mod_ci/controllers.py

---
`previous_commit` and `last_commit` almost felt synonymous.

[IMPROVEMENT] Super-minor refactoring, making variable name more legible.

---

mod_ci/controllers.py
mod_sample/controllers.py
mod_sample/models.py
mod_upload/controllers.py
run.py
templates/sample/list_issues.html

---
It depends a lot on org repo settings to fetch all inf. including issue id based on sample id.
So i saved sample id along with issue id in the database sample_issue.

[FIX] github issue listing migrated to database

---

install/install.sh
mod_upload/controllers.py
mod_upload/forms.py

---
#15 
* USING python-magic, found mimetype
* map mimetype to extension using mimetypes
* block those mapped extensions which are forbidden

[IMPROVEMENT] added mimetype check to sample

---

mod_sample/controllers.py
mod_sample/media_info_parser.py
templates/sample/sample_info.html

#88 
---
Added exception in media info to handle not media info

[FIX] hide media info when not found

---

install/ci-vm/ci-linux/ci/runCI

---
#55 #18 
added build checks for builddebug, autoconf, cmake

[IMPROVEMENT] added build checks for builddebug, autoconf, cmake

---

install/ci-vm/ci-linux/ci/runCI
install/ci-vm/ci-windows/ci/runCI.bat

---
cmake check is added in windows ci
Install cmake for windows from https://cmake.org/files/v3.9/cmake-3.9.1-win64-x64.msi [https://cmake.org/download/]
#55 #18

[IMPROVEMENT] Add cmake check on Windows CI 

---

mod_ci/controllers.py

[FIX] fixed issue updating to github of windows testing

---

mod_ci/controllers.py

---
it was saving value in wrong variable

[FIX] fix in pr on self commit check

---

mod_auth/controllers.py
mod_auth/models.py
mod_ci/controllers.py
mod_ci/models.py
mod_deploy/controllers.py
mod_home/controllers.py
mod_home/models.py
mod_regression/controllers.py
mod_regression/models.py
mod_sample/controllers.py
mod_sample/models.py
mod_test/controllers.py
mod_test/models.py
mod_upload/controllers.py
mod_upload/models.py

---
#21 
- Added documentation to
- mod_ci/models.py
- mod_ci/controllers.py
- mod_test/models.py
- mod_test/controllers.py
- mod_sample/models.py
- mod_sample/models.py
- mod_sample/controllers.py
- mod_home/models.py
- mod_home/controllers.py
- mod_deploy/models.py
Added header doc and wherever required

[IMPROVEMENT] Added documentation to various models and controllers

---

mod_sample/models.py
mod_upload/controllers.py
mod_upload/forms.py

---
Extension prediction is not always correct
Add these to mimetype_forbidden db:
a) application/x-dosexec
b) application/x-msdos-program
c) text/x-shellscript
d) text/x-msdos-batch
e) application/x-msi

[FIX] Updated sample upload to check mimetype along with extension

---

mod_ci/controllers.py

---
added check on progress step in progress reporter.
if step is less than what already happened then make that canceled.

[FIX] fixed multiple instances of test progress on vm crash

---

mod_ci/controllers.py
mod_ci/cron.py

---
It is possible that we encounter race condition while running windows and linux vm together.
Better will be to run them separately. 
added checks on each testing ehther any other vm is running or not
if not:
I check whether it is at the top of kvm or not.

[FIX] serialize windows and linux testing

---

mod_ci/controllers.py

---
Previous PR has some small mistake.
I need to check kvm to check running tests and then check test to execute new tests.

[FIX] Check first kvm and then test

---

install/sample_db.py

---
This fixes the issue for local installation for platform, there were 2 missing imports for sample_db.py file.
This PR adds those missing imports and makes local installation error free

[FIX] Add missing imports to sample_db.py file

---

install/installation.md

---
Everything was pretty self explanatory except for cygwin set up

[IMPROVEMENT] Edited installation.md for ease

---

static/fonts/fontawesome-webfont.svg

-  [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/sample-platform/blob/master/.github/CONTRIBUTING.md).
---
Updated the files, checked them briefly. Sadly, this is my first time using GitHub, so my work may be very rough around the edges. It seems from my POV that fontawesome has already been updated.

[IMPROVEMENT] Updated Font Awesome from 4.5.0 to 4.7.0

---

database.py

**[FIX]**
- [.] I have read and understood the [contributors guide](https://github.com/CCExtractor/sample-platform/blob/master/.github/CONTRIBUTING.md).
- [.] I have checked that another pull request for this purpose does not exist.
- [.] I have considered, and confirmed that this submission will be valuable to others.
- [.] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [.] I give this submission freely, and claim no ownership to its content.
- [.] I have used the project briefly.
---
Fixed typos in comments in database.py file

Fixed typos in comments/output

---

install/installation.md

---
Improved Linux section of installation.md
Removed a troubleshooting tip that was (almost) always required and instead incorporated it in the cloning command. 
Added a command to change directory to the one which is recommended.

**[IMPROVEMENT]** Updated installation.md

---

install/install.sh
requirements.txt

---
Replaces the hard-coded packages in the install.sh with a requirements file. This will help when setting up automated builds (e.g. for Travis)

[IMPROVEMENT] Switch to pip requirements file

---

.coveragerc
.travis.yml
README.md
tests/TestLogConfiguration.py
tests/TestMailer.py

---
- Add Travis integration
- Add codecov integration
- Add tests for the mailer and the log_configuration

[IMROVEMENT] Add a couple of unittests

---

.pep8speaks.yml

---
Add config for pep8speaks 👍

[IMPROVEMENT] Add config for pep8speaks

---

mod_ci/controllers.py

Fix missing pr nr causing number to be set to 0

---

mod_ci/controllers.py

- Removes the commit from the PR's if it's no longer applicable
- No longer keeps track of the GH status if the commit is empty
- Trigger new tests only after posting current status instead of otherwise.

Rework some code to potentially fix the non-posting issue

---

mod_ci/controllers.py

---
Fixes #126 by ensuring that the "synchronize" status also has a commit (and gh_commit to post it to).

[BUG] fixes testing to new pushes to pr

---

static/css/app.css

- [ x] I have considered, and confirmed that this submission will be valuable to others.
- [ x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x ] I give this submission freely, and claim no ownership to its content.
- [ x] I have used the project briefly.
---

[FIX] Update app.css

---

templates/menu.html

---
The menu has weird spacing and as far as I can see, the "row column" classes are not required there.
Above = After
Below = Before
**Desktop**
**Phone**

[IMPROVEMENT] Fix sidebar CSS.

---

bootstrap_gunicorn.py
config_parser.py
database.py
decorators.py
install/init_db.py
install/sample_db.py
log_configuration.py
mailer.py
mod_auth/controllers.py
mod_auth/forms.py
mod_auth/models.py
mod_ci/controllers.py
mod_ci/models.py
mod_deploy/controllers.py
mod_home/controllers.py
mod_home/models.py
mod_regression/controllers.py
mod_regression/models.py
mod_sample/controllers.py
mod_sample/media_info_parser.py
mod_sample/models.py
mod_test/controllers.py
mod_test/models.py
mod_test/nicediff/diff.py
mod_upload/controllers.py
mod_upload/forms.py
mod_upload/models.py
run.py

Simplifies/shortens all lines where possible using the new 120 characters as max line length.
This should improve readability, and prepares for other refactors in the (near) future.

Line simplifications

---

mod_ci/models.py
templates/menu.html

- [] I have never used the project.
---
Includes their userID so that it works even when they change their username.

[IMPROVEMENT] Added Data Model for BlockedUsers

---

mod_ci/models.py

---
Either length need to be specified 
or we can set the comment in Text format

[FIX] Blocklist Comment needed to be in Text format

---

mod_home/models.py

[IMPROVEMENT] Minor Typographical Fix

---

README.md
install/installation.md

[IMPROVEMENT] Minor Documentation Improvement

---

mod_auth/controllers.py

---
Use convertors instead of explicit casting.

[Improvement] Use convertors instead of explicit casting.

---

mod_ci/controllers.py

---
Update badge on commit, not PR.

[FIX] Update badge on commit, not PR.

---

mod_ci/controllers.py

- Simplify lines that could be put on one line with new max-length
- "true" if foo else "false" type of constructs simplified
- Simplified handling for PR's (merged if blocks together)

Simplify some lines

---

README.md
mod_ci/controllers.py
mod_ci/forms.py
templates/ci/blocked_users.html

[FEATURE] Added BlockedUsers Management

---

mod_ci/controllers.py

[IMPROVEMENT] Documented blocked_users processing and fix typos

---

install/ci-vm/ci-linux/ci/bootstrap
install/ci-vm/ci-linux/ci/variables-sample
mod_deploy/controllers.py

---
Have added a variable for it as well as pulling the specific file from the origin, I hope this is the correct method.

[IMPROVEMENT] Update runCI from NFS share

---

mod_ci/controllers.py
mod_ci/forms.py
mod_ci/models.py
templates/ci/blocked_users.html

[IMPROVEMENT] Made variable names compliant

---

templates/ci/blocked_users.html

[IMPROVEMENT] Fix flash duplicacy

---

mod_ci/controllers.py
mod_ci/forms.py
templates/ci/blocked_users.html

---
Remove conflict when submitting both forms by adding another check and making the field names unique.

[IMPROVEMENT] Fix remove_user_form processing

---

mod_ci/controllers.py

[FIX]Changed from remove() to delete()

---

mod_ci/controllers.py
mod_home/models.py

---
#174 
Firstly release number is updated using tagline.
and then regression test table is updated.
References:
[https://developer.github.com/v3/activity/events/types/#releaseevent](https://developer.github.com/v3/activity/events/types/#releaseevent)

[IMPROVEMENT] Adding release webhook to update version and baseline regression tests

---

mod_ci/controllers.py

[FIX] Added merge conflict handling

---

mod_test/nicediff/diff.py

[FIX]Fix Infinite recursion bug in comparison script

---

static/css/app.css
templates/base.html
templates/ci/blocked_users.html
templates/regression/index.html
templates/upload/ftp_index.html
templates/upload/upload.html

---
Added some fixes to foundation upgrade, Hoping it will fix all.

[FIX] Added some foundation upgrade layout fixes

---

static/css/app.css
templates/base.html

---
Due to saved cookies, i forgot this change. Fixed now

[FIX] fixed footer layout

---

templates/base.html

---
Footer is now in align to the content of the page.

[FIX] Footer Indentation Fixed

---

mod_home/models.py

---
Fix this bug otherwise the version webhook will give error

[FIX] small fix in mod_home models.py

---

mod_ci/controllers.py

---
Based on the Discussions we had on the Slack Chat it would be a good idea since we have a mailing list to send the GitHub issues to the mailing list.
Subject will look like: `GitHub Issue #210`
Body will look like
```
[QUESTION] set subtitle timing from live stream timestamp - jakubvojacek
body of the issue....
```

[FEATURE]Send Emails to Mailing List

---

mod_ci/controllers.py

---
It is always a best practice to pass as few arguments as possible into a function, hence an argument has been reduced where possible.
Also, the times the function will be executed has been reduced by checking the condition before entering the function.
Few other changes according to PEP8 standards and removal of unused variables.
*Change severity: trivial*

[IMPROVEMENT]Refactor new issue mail code

---

README.md

---
Updated readme to include words about GSoC '18.
**change severity: minuscule**

Update README to include GSoC '18

---

install/installation.md

---
Added requirement of python 3

[FIX] update installation.md [Python 3 installation required]

---

Pipfile
Pipfile.lock

---
Incorporates Pipenv standards alongside requirements.txt
fixes #204 
**change severity: low**

[FEATURE] Shift to pipenv

---

mod_ci/controllers.py

---
added none test result check

[FIX] fixed issue of wrong result report in pr comments

---

mod_ci/controllers.py

---
Close connection to libvirt after completion.

Close connection to libvirt.

---

mod_test/controllers.py
templates/auth/manage.html
templates/test/by_id.html
templates/test/index.html
templates/test/list_table.html
templates/upload/process_table.html

---
- Added Select option to see tests between main repo and fork repos
- All tables are now mobile responsive.
- Improved account form structure.

[FIX] Adding ui features and fixes including table support and form fixes

---

mod_sample/controllers.py
tests/base.py
tests/test_sample/TestControllers.py

---
- release status variable update fix
- added unittesting of sample controllers

[FIX] fixed sample release status + adding unittesting of sample controllers

---

mod_customized/controllers.py
mod_test/controllers.py
templates/test/list_table.html
tests/base.py
tests/test_ci/TestControllers.py
tests/test_test/TestControllers.py

---
1. Added restart and stop button for admin for any test.
2. Users can restart and stop their tests in customized tests panel.

[FEATURE] Adding Restart / Stop Tests for admin and user

---

mod_upload/controllers.py
tests/base.py
tests/test_upload/TestControllers.py

[IMPROVEMENT] added mod_upload unittesting

---

mod_ci/controllers.py
mod_customized/controllers.py
mod_test/controllers.py

---
Documentation of some functions of:
- mod_customized
some functions of:
- mod_test
- mod_ci

[IMPROVEMENT] added documentation of customized module and some other modules

---

mod_test/controllers.py

[FIX] svg test being queued bug

---

mod_test/controllers.py

[FIX] for previous fix

---

mod_ci/controllers.py

[FIX] Fixed String compare issue

---

README.md

- [] I have never used the project.
- [] I have used the project briefly.
---

[IMPROVEMENT] Update README GSoC info.

---

mod_ci/controllers.py

add missing parenthesis and stop triggering OCD
---
stop trigger

[IMPROVEMENT] Update Comment

---

mod_ci/controllers.py
tests/test_ci/TestControllers.py

Edit message in inform_mailing_list and Add Unit Test

---

mod_regression/controllers.py
tests/test_regression/TestControllers.py

---
Work in Progress PR. Need to ask for user confirmation before deletion

[FEATURE] Feat/delete regression

---

mod_regression/controllers.py
mod_regression/forms.py
templates/regression/category_add.html
tests/test_regression/TestControllers.py

[FEATURE] Added option to add category

---

mod_regression/controllers.py
templates/regression/category_edit.html
tests/test_regression/TestControllers.py

Added option to edit category

---

templates/base.html

---
I've added Open Graph Properties which is very useful for Url Unfurling.
You can read more about it here: http://ogp.me/

[FEATURE] Add Open Graph Properties

---

mod_regression/controllers.py
templates/regression/test_edit.html
tests/test_regression/TestControllers.py

[FEATURE] Added option to edit regression tests

---

.idea/inspectionProfiles/profiles_settings.xml
mod_regression/controllers.py
templates/regression/test_delete.html
tests/test_regression/TestControllers.py

---
Now you are able to confirm if you want to delete a test

[IMPROVEMENT] confirmation for Test deletion

---

mod_regression/controllers.py
templates/regression/test_delete.html
tests/test_regression/TestControllers.py

---
- Check if user is logged in before checking roles, fixes 500 when not logged in.
- Delete test instead of trying to delete ... category (?).

[FIX] Fix regression test deletion.

---

mod_regression/controllers.py

---
- Give contributors access to regression test/category operations.

[FIX] Give contributors access to regression test/category operations.

---

mod_ci/controllers.py
tests/base.py
tests/test_ci/TestControllers.py

---
- Follow https://developer.github.com/v3/activity/events/types/#releaseevent
- Write Unittests testing the webhook feature
https://developer.github.com/v3/activity/events/types/#releaseevent

[FIX] Fixed bug in release webhook

---

.gitignore
Pipfile
Pipfile.lock
install/install.sh

---
PEP8 linter has been added to Pipfile development requirements.

[FEATURE] Add pep8

---

install/install.sh

---
The PR sanitizes the current install.sh and implements contemporary methods of handling shell scripts. 
[ShellCheck](https://www.shellcheck.net/) was used to modernise the code.
Pep8 was also added to ensure local sanity check for Python.
NOTE: There are reports of unused variables but due to unholistic knowledge, they were not removed.

[IMPROVEMENT] Sanitize Install.sh Using Shellcheck

---

.github/CONTRIBUTING.md
Pipfile
Pipfile.lock
README.md
requirements.txt

---
The PR provides following improvements:
- Add testing dependencies to Pipfile and requirements.txt
- Add instructions for running tests locally
- Recommend users to run tests before submitting PR

[Improvement] Add Instructions For Local Testing

---

.github/ISSUE_TEMPLATE.md

[IMPROVEMENT] Comment out help text in issue template

---

templates/home/index.html

---
Since we are not maintaing sourceforge repo anymore and switching to github releases, we should maintain the link to releases on sample platform homepage.

[IMPROVEMENT ]replace sourforge with github release

---

mod_ci/controllers.py

---
@canihavesomecoffee Please merge this ASAP :)

fix argument mismatch

---

mod_ci/controllers.py

---
The PR adds logging to release section of the CI so that we can get important information and also see if the statement gets triggered.

add logging for release webhook

---

mod_deploy/controllers.py

**My request with the project is as follows (check one):**
---
Useful for anyone trying to set up their own instance that auto updates from GitHub given that the default webhook content type is x-www-form-urlencoded. I learnt this the hard way

[IMPROVEMENT] Add webhook content type comments

---

mod_auth/forms.py
mod_deploy/controllers.py
tests/base.py
tests/test_auth/TestControllers.py
tests/test_auth/TestForms.py
tests/test_ci/TestControllers.py
tests/test_deploy/TestControllers.py

---
The PR brings the following changes:
- Add unit-tests for mod_deploy and mod_auth.
- Segregate methods used by multiple test files into base.py
- Update to existing changes since they were not triggering `/deploy` properly due to not having set correct environment and headers.
- Remove ununsed code and improve existing methods.
NOTE: Each commit contains a brief bulleted explanation if required.
concerns #284

[IMPROVEMENT] Add and Improve Unit-Tests

---

mod_sample/controllers.py
tests/test_sample/TestControllers.py
tests/test_sample/TestMediaInfoParser.py

---
The PR brings in the following changes:
- Write unit-tests for mod_sample controllers.

add unit tests for mod_sample

---

tests/test_test/TestControllers.py

---
The PR adds unittests for mod_test.
NOTE: Functions with decorator `@template_renderer()` have been skipped.

add unittests for mod_test

---

tests/base.py
tests/test_auth/TestControllers.py
tests/test_upload/TestControllers.py
tests/test_upload/TestProgressFTPUpload.py

---
The PR adds unittests for mod_upload.

add unittests for mod_upload

---

README.md
mod_auth/controllers.py
mod_auth/forms.py
mod_auth/models.py
mod_ci/controllers.py
mod_ci/models.py
mod_customized/controllers.py
mod_customized/models.py
mod_deploy/controllers.py
mod_home/controllers.py
mod_home/models.py
mod_regression/controllers.py
mod_regression/models.py
mod_sample/controllers.py
mod_sample/media_info_parser.py
mod_sample/models.py
mod_test/controllers.py
mod_test/models.py
mod_test/nicediff/diff.py
mod_upload/controllers.py
mod_upload/forms.py
mod_upload/models.py
mypy.ini
run.py

---
The PR adds the following changes:
- Add basic annotations with the help of `monkeytype`.
- Add basic annotations with the help of `pytype`.
- Put ignore statement for inappropriate and unnecessary checks which hamper dynamic flexibility.
- Improve static typing by manual inspection.
fixes #281

Add Annotations To All Modules

---

mod_regression/controllers.py
mod_sample/controllers.py
mod_test/controllers.py
tests/TestUtility.py
tests/test_regression/TestControllers.py
tests/test_sample/TestControllers.py
tests/test_test/TestControllers.py
utility.py

---
- We have the similar function at multiple places serving the same purpose.
- It is made available in the utility module and can be accessed anywhere.

[IMPROVEMENT] move `serve_file_download` to utility

---

templates/home/about.html

[FIX] License name to ISC

---

templates/test/by_id.html

[IMPROVEMENT] Show commit for both test types

---

install/install.sh

[fix/improvement]fixed the MYSQL condition issue #341 add other checks to the installer and improvement to  #342

---

install/install.sh
mod_auth/controllers.py
mod_ci/controllers.py
mod_customized/controllers.py
mod_deploy/controllers.py
templates/auth/manage.html
templates/sample/list_issues.html
templates/sample/sample_info.html
tests/base.py
tests/test_auth/TestControllers.py
tests/test_customized/TestControllers.py
tests/test_deploy/TestControllers.py

Signed-off-by: Aadi Bajpai <me@aadibajpai.me>
---
one step closer to perfection

[IMPROVEMENT] Github → GitHub

---

mod_ci/controllers.py
mod_test/models.py
tests/base.py
tests/test_ci/TestControllers.py
tests/test_deploy/TestControllers.py

---
The PR aims to solve the issue of failing tests which have been brought by the latest commits to the sample-platform.

[FIX] Failing Tests

---

test-requirements.txt

---
Attempt to fix broken unittests.

[FIX] Update test-requirements.txt

---

requirements.txt

Remove ip address dependency
---

Remove ip address dependency

---

mod_test/controllers.py
tests/test_test/TestControllers.py

---
Is_xhr header is deprecated. I have replaced it with the current alternative.

is_xhr header fix

---

install/installation.md

---
Update the troubleshooting part, regarding the possible errors on libvirt package.

updated installation guide

---

mod_test/nicediff/diff.py

---
In reference to https://github.com/CCExtractor/sample-platform/pull/398#issuecomment-631727905

[FIX] Update diff.py

---

tests/TestConfigParser.py
tests/TestLogConfiguration.py
tests/TestMailer.py
tests/TestRun.py
tests/test_ci/TestControllers.py
tests/test_customized/TestControllers.py
tests/test_deploy/TestControllers.py
tests/test_sample/TestControllers.py
tests/test_upload/TestControllers.py
tests/test_upload/TestProgressFTPUpload.py

[FIX] Mock Module error in Github Actions

---

mod_test/controllers.py

[FIX]  Diff not showing in browsers.

---

.pycodestylerc
mod_regression/controllers.py
templates/regression/test_view.html
tests/base.py
tests/test_regression/TestControllers.py

**[FIX]**
---
Remove duplicates for the file hashes in the Select Field and also show got values for last 50 test runs if not null.

Remove duplicates for the file hashes in the SelectField

---

templates/test/by_id.html

[FIX] Show log file even when build partially succeded

---

mod_sample/media_info_parser.py
tests/test_sample/TestMediaInfoParser.py

[FIX] MediaInfo not showing up on the platform

---

mod_test/controllers.py
tests/test_test/TestControllers.py

[FIX] Incorrect number of queued tests

---

.pydocstylerc
mod_test/nicediff/__init__.py
mod_test/nicediff/diff.py
tests/TestConfigParser.py
tests/TestLogConfiguration.py
tests/TestMailer.py
tests/TestRun.py
tests/TestUtility.py
tests/__init__.py
tests/base.py
tests/test_auth/TestControllers.py
tests/test_auth/TestForms.py
tests/test_ci/TestControllers.py
tests/test_ci/TestMarkdown.py
tests/test_customized/TestControllers.py
tests/test_deploy/TestControllers.py
tests/test_home/TestControllers.py
tests/test_regression/TestControllers.py
tests/test_regression/TestUpdateRegression.py
tests/test_sample/TestControllers.py
tests/test_sample/TestMediaInfoParser.py
tests/test_test/TestControllers.py
tests/test_test/TestDiff.py
tests/test_upload/TestControllers.py
tests/test_upload/TestProgressFTPUpload.py

---
Hello, I want to contribute to this project as a part of GSoC 2021.
I started to fix issue #304, now I decreased from ~380 errors to ~130. I also turned off module-level docstrings, so now we have 110 errors.

[IMPROVEMENT] Fix docstring

---

mod_sample/forms.py
mod_upload/forms.py
templates/sample/edit_sample.html
tests/test_sample/TestControllers.py

[FIX] edit sample 

---

install/ci-vm/ci-linux/ci/runCI

---
Remove redundant tests and add rust flag for cmake build

Update linux CI script

---

install/ci-vm/ci-linux/ci/runCI

---
Update runCI to enable ocr for cmake builds

Enable ocr for linux ci

---

install/ci-vm/ci-linux/ci/runCI

Use rust build by default and release build

---

install/ci-vm/ci-linux/ci/runCI
install/ci-vm/ci-windows/ci/runCI.bat

Update windows CI script

---

install/ci-vm/ci-windows/ci/runCI.bat

add rust build step

---

install/ci-vm/ci-windows/ci/runCI.bat

---
Remove unnecessary build step for rust code

Remove unnecessary build step

---

mod_test/models.py
requirements.txt

Pin WTForms to 2.3.3

---

install/install.sh

---
This PR fixes the issue mentioned in #606

[FIX] Bug Fixes Related to Installation

---

decorators.py
mod_auth/controllers.py

---
Signup button added in menu. Fixes #505

[IMPROVEMENT] Signup button added in menu. Fixes #505

---

.gitignore
README.md
install/install.sh
requirements.txt

---
This PR aims to fix some of the issues that I faced during my installation for the platform:
1. Some outdated packages have been updated in ./install/install.sh
2. To fix some dependency issues, 2 dependencies have been pinned to requirements.txt
The second issue is also mentioned in #652 .

[FIX] Some Install Issues Fixed

---

requirements.txt

---
Update requirements for requests, python-magic, and mypy.

[improvement] merge dependabot requirement updates

---

install/installation.md

---
This pull request adds up the documentation that provide the steps to troubleshoot a broken platform installation and fix it.

[IMPROVEMENT] Add documentation to troubleshoot platform installation

---

install/ci-vm/ci-linux/ci/runCI
install/ci-vm/ci-windows/ci/runCI.bat
mod_ci/controllers.py
requirements.txt
test-requirements.txt
tests/test_auth/TestControllers.py
tests/test_ci/TestControllers.py

---
Sync GSoC-22-dev and master branch.

update GSoC-22-dev with master

---

.gitignore
install/ci-vm/ci-windows/rclone_sample.conf
install/install.sh
requirements.txt

---
This pull request modifies `install/install.sh` file to generate GCP related config data and generate rclone.conf files as mentioned in #696.
Note: However there could be still many improvements like installation of MySQL through the fails and other gunicorn installation related bugs, which need to be fixed with #67, detailed report would be added to that issue soon.

[IMPROVEMENT] Modify install.sh to generate GCP related config files

---

install/ci-vm/installation.md

---
Add more information to make it easier to set up the GCP bucket for new deployment instances of sample-platform.
-- Notes
1. Just after the installation completes successfully all we have to do is to transfer ccx_testsuite to TestData/ci-linux and similarly for the windows folder
2. Using `gcloud`, migrate all samples and results in folders TestFiles and TestResults to the created bucket
3. Create a MySQL dump of the existing database to replicate the sample on the new machine.

[improvement] add instructions related to setting up bucket

---

README.md
install/ci-vm/installation.md
install/install.sh
install/installation.md

---
This pull request provides step-by-step documentation required for setting up a new platform server on a Google Cloud VM instance.

[IMPROVEMENT] Add documentation related to installation of new platform on GCP

---

README.md
install/ci-vm/installation.md
install/install.sh
install/installation.md

Thealphadollar patch 1

---

install/ci-vm/ci-linux/ci/runCI
install/ci-vm/ci-linux/startup-script.sh
install/ci-vm/ci-windows/ci/runCI.bat
install/install.sh
requirements.txt

---
This pull request fixes some permission related, some testsuite configuration-related and other issues from #690.

[FIX] Fixes for tests on GCP VM instances

---

install/nginx.conf

---
This PR fixes the removal of some required configurations in `nginx.conf` done in #711.

[FIX] Add missing nginx configuration to serve files

---

install/install.sh

---
This PR includes the following changes:
- Create a function `userInput` to take inputs from the user, and based on the function arguments, we can mark the variables as required or not.
- In case the variables are marked not required and user doesn't set them, we log variable-specific warnings to the user.

[IMPROVEMENT] Modify install.sh to read input variables and log related warnings if variable not set

---

install/install.sh
requirements.txt

---
This pull request patches python installation for platform to version 3.9, currently `apt-get install python3` of GCP VMs would not install python 3.9, as they come with python 3.10 pre-installed.

[IMPROVEMENT] Patch python version to 3.9 to avoid python 3.10 installation

---

install/install.sh
mod_ci/controllers.py
mod_ci/cron.py
tests/test_ci/TestControllers.py

---
This PR changes the deployment of the platform to be uni-regional instead of multi-regional; it would have the following benefits:
- Reduction of the monthly cost.
- Operations within a region a comparatively faster.

[FIX] Change VM location to us-central1, Fix SQLAlchemy errors

---

mod_ci/controllers.py
mod_test/models.py
tests/test_ci/TestControllers.py

---
This pull request initiate cancelling of tests if GitHub actions fails along with posting on GitHub.
This pull request allow disallow picking of tests by cron job before completion of their GitHub overflows.

[IMPROVEMENT] Cancel failing test with build failure

---

mod_ci/controllers.py
mod_ci/cron.py
mod_customized/controllers.py
mod_deploy/controllers.py
mod_test/controllers.py
mod_upload/controllers.py
requirements.txt
tests/base.py
tests/test_auth/TestControllers.py
tests/test_ci/TestControllers.py
tests/test_customized/TestControllers.py
tests/test_deploy/TestControllers.py
tests/test_upload/TestControllers.py

---
This pull request migrates the old code base from githubpy to PyGithub as githubpy is no longer being maintained
This PR is a part of #761.

[IMPROVEMENT] Migrate from githubpy to PyGithub

---

README.md

---
I think it's the recent move to `nose2` that broke the command. So I think this fixes it.

[IMPROVEMENT] fix the local testing instructions

---

mod_ci/controllers.py

---
This is a PR to fix type checking and the default value assigned in #810 for `update_status_on_github`

[FIX] Use NotSet instead of _NotSetType(), add mypy line ignore

---

mod_ci/controllers.py

---
This PR is to move the code for moving the section of code that is currently giving the worker timeout at the last
So that we can fix and debug bot comments further if required

[FIX] Temporary Solution(Bot Comments) - Move code to update avg. time at last

---

bootstrap_gunicorn.py

---
This PR is to increase the gunicorn worker timeout to 120s, we should later reconsider decreasing the timeout when we would enable support for asynchronous processes...

[FIX] Increase gunicorn worker timeout

---

mod_ci/controllers.py

---
This PR is tested, you may check comments on [this PR](https://github.com/CCExtractor/ccextractor/pull/1509)

[FIX] Fix bot comments on PRs

---

.github/workflows/sp-deployment-pipeline.yml

[FEATURE] Add checks to run deploy workflow, post other workflows

---

install/installation.md

---
This PR is to update the algorithm used for SSH keys generation, to use more modern and secure algorithms

[IMPROVEMENT] Change documentation for SSH key algorithm used

---

migrations/versions/a5183973c3e9_.py
templates/regression/index.html

[FIX] Change boolean type from bit to tinyint 

---

mod_ci/controllers.py

---
This PR adds a check on workflow runs to be within Linux and Windows
This is because CCX now has Github actions for MacOS also, and those are interfering, example here: https://github.com/CCExtractor/ccextractor/pull/1551
GH Actions are complete but it is still showing not complete...

[FIX][URGENT] Add checks for workflow name in Linux and Windows

---

install/installation.md
mod_ci/controllers.py
run.py
tests/base.py
tests/test_ci/test_controllers.py

---
Closes #862 
Also, this PR helps to determine if GCP instance creation was successful or not.

[IMPROVEMENT] Add documentation to add cron job, nit changes 

---

mod_regression/controllers.py
tests/test_regression/test_controllers.py

[IMPROVEMENT] Populate existing data on category edit endpoint

---

mod_ci/controllers.py
mod_ci/models.py
templates/ci/pr_comment.txt
tests/test_ci/test_controllers.py

---
This PR Is to now compare the test results from master branch instead of whole tests
Sample Comment: https://github.com/CCExtractor/ccextractor/pull/1509#issuecomment-1705458230

[IMPROVEMENT] Compare tests with master branch for PRs

---

mod_ci/controllers.py
tests/test_ci/test_controllers.py

---
This PR is to strictly enforce use of `update_status_on_github` to update status on github
And fix blocked_users endpoint and increase test coverage

[IMPROVEMENT] Use update_status_on_github to report status 

---

mod_ci/controllers.py
mod_test/controllers.py
tests/test_ci/test_controllers.py

---
This PR is to fix the difference in PR comments and the platform test results
For instance, now see the [bot comment](https://github.com/CCExtractor/ccextractor/pull/1509#issuecomment-1722287079) and the [platform result](https://sampleplatform.ccextractor.org/test/4734)

[FIX] Fix bot PR comments & platform test results difference

---

mod_regression/controllers.py
mod_sample/controllers.py
mod_test/controllers.py

---
Prevent anyone from downloading data except when logged in.

feat: Change downloads to only work when logged in
