mod_test/models.py

If the timezone if none it will 
1. Find and associate localtime zone to it.
2. Convert it to UTC.
But if timezone is not None , it checks if tzinfo is  None
1. Associate it with UTC timezone.

Corrected timezone handling.

---

mod_test/models.py

The timestamp is made tz aware on query using orm.reconstructor.

Made a reconstructor for TimeZone awareness.

---

mod_test/nicediff/diff.py

Blank table elements were being created while skipping the lines which had no difference in them.

Fixes creation of blank table divisions.

---

mod_auth/forms.py

#35 
fixed-"Input type of login email field should be email instead of text"

Email form type changed to email

---

mod_ci/controllers.py

---
we have to set tzinfo = none where its not none. I just forgot to add not. :)

[FIX] forgot to add "not" in previous pr

---

templates/test/by_id.html

---
Apparently Chrome is smart enough to compensate missing bracket, but Safari is not. Added the missing bracket.

[FIX] Categories not toggling on some browsers.

---

mod_ci/controllers.py
mod_test/controllers.py

---
In mod_ci, it is check the platform according to that, 2 keys have been added, one controlling time for one platform and one key for another, if more platforms will be added, it will be handled automatically by adding key 'average_time_{platform}'.
In mod_home, only tests in kvm have been considered whose platform match with the test handled by the user.

[FIX] Predicted waiting time adapted to platform

---

mod_ci/controllers.py

---
When the platform starts a new test after finishing a previous one
It sleeps for 60 seconds
But as it's not in a separate thread
It throws a 504 or 502 and kills the worker after 30 seconds
If we start a new test and do a sleep, it needs to be in a separate thread

[FIX] adding threading to start new test when previous test in completed

---

static/css/app.css

---
Fixed the broken layout, working smoothly in both desktop and mobile layout.

Fixed - [Bug] Foundation upgrade broke lay-out

---

.gitignore
mod_test/nicediff/diff.py
tests/TestDiff.py

---
- Escape quotes (`"` / `'`) along with HTML tags.
- Note : `cgi.escape` is now deprecated, and Python 3 offers `html.escape` in replacement. So, while porting to Python 3, this needs to be kept in mind.
- Added a unit test to check if generated diff is consistent with expected diff.
Since `expected_diff` contains generated HTML diff, that line is quite large and I am expecting that this will break some PEP8 formatting rule. If someone can help avoid it, it'd be great! :)
---
Running the test : 
```
Testing started at 7:00 PM ...
/venv/bin/python /Applications/PyCharm.app/Contents/helpers/pycharm/_jb_unittest_runner.py --target …
```

[IMPROVEMENT] Add a unit test for diff generator and some related minor improvements.

---

mod_test/nicediff/diff.py

---
Since we're upgrading the platform to Python 3.5+, replaced deprecated `cgi.escape`.
Note: `html.escape` defaults to `quote=True`

[IMPROVEMENT} Completed TODO : Replace deprecated cgi.esacpe with html.escape (Python 3.2+)

---

mod_upload/controllers.py
run.py
templates/upload/process_table.html

#200 
---
Using OS basename, we can find the name of that file and just display that instead of displaying full path. Same thing when storing in QueuedSamples.

[FIX] fixed issue of full path in queued samples

---

mod_auth/controllers.py
run.py

---
- ResourceWarning: unclosed file <_io.BufferedReader name='secret_csrf'>
install_secret_keys(app)
- PendingDeprecationWarning: HMAC() without an explicit digestmod argument is deprecated.
return HMAC(key, msg, digestmod)

[IMPROVEMENT] Fix few warnings.

---

static/css/app.css

---
Now icons stay with the progress bar and font size has been reduced to accommodate complete progress bar on smaller screen sizes. 
Fixes bug (#225)
Current css:
After fix:

[FIX] Responsive progress bar

---

.coveragerc

---
The PR addresses the issue that install directory and it's contents have a say in the test coverage report though they are not intended to be covered by unit tests. Hence, it is only wise to have it in the excluded code.
Discussed with @canihavesomecoffee .

[FIX] remove install dir from test coverage

---

.coveragerc

---
https://github.com/CCExtractor/sample-platform/blob/dbd11465f8d31eed10071c2df39dfd6a0f5dfa83/mod_ci/models.py#L29-L32
If we look at a code block like this in all files that have Database Models, nowhere are they actually called in the production code and most of the time it's only used to represent the Entry of the Database when running flask shell for example. So if we remove it from code coverage the test coverage will increase and won't be measuring it, since it won't be needed to test it.

[IMPROVEMENT] Ignore the `__repr__` function since it's only used for represantation in .coveragerc

---

.travis.yml
Pipfile
mod_ci/controllers.py
tests/test_ci/TestControllers.py
tests/test_ci/TestMarkdown.py

---
The PR allows for smoother operation in response to the trigger of `release` webhook.
- Delete CCEx version when a release is deleted or unpublished.
- Update CCEx version when a release is edited or published.
- We do not alter the existing tests since they are based on the latest commit and not release.
fixes #295

[FIX] Inconsistency In CI for Release Webhook

---

tests/test_ci/TestControllers.py

---
The PR currently adds the following:
- unittest to mod_ci controllers
- skip tests for methods that have `check_access_rights` decorator
- reduced testing time by importing commonly used modules globally
- improve documentation for the tests by a marginal amount

add unittests for mod_ci controllers

---

mod_ci/controllers.py
mod_ci/cron.py

---
The PR fixes bug introduced by #323 where in the process launched by start_platform was getting out of context.
```
[INFO] Run the cron for kicking off CI platform(s).
[INFO] setting Linux virtual machine process...
Traceback (most recent call last):
File "/var/www/sample-platform/mod_ci/cron.py", line 33, in <module>
cron()
File "/var/www/sample-platform/mod_ci/cron.py", line 30, in cron
start_platforms(db, repository)
File "/var/www/sample-platform/mod_ci/controllers.py", line 95, in start_platforms
linux_process = …
```

fix out of context bug

---

mod_ci/controllers.py
tests/test_ci/TestControllers.py

---
The PR breaks down the `progress_reporter` function based on the type of the request and adds tests.
Due to high number of mocking in type==progress, it is not advisable to write unit-test for it.
fixes #322

[IMPROVEMENT] Simplify progress reporter And Add Corresponding Tests

---

mod_test/controllers.py

---
Fix value error caused as per the following stack trace.
```
[2019-08-13 20:30:14,375] ERROR in app: Exception on /test/2171 [GET]
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
reraise(exc_type, exc_value, tb) …
```

fix value error

---

Pipfile
requirements.txt

---
Bump GitPython dependency from 2.1.11 to 3.1.0, fix unittests on Travis.

[FIX] Bump GitPython dependency from 2.1.11 to 3.1.0

---

.travis.yml
README.md
database.py
install/init_db.py
install/sample_db.py
mailer.py
manage.py
mod_ci/controllers.py
mod_ci/cron.py
mod_sample/controllers.py
mod_test/controllers.py
mod_upload/controllers.py
run.py
tests/test_ci/TestControllers.py
tests/test_customized/TestControllers.py
tests/test_regression/TestUpdateRegression.py
tests/test_sample/TestControllers.py
tests/test_test/TestControllers.py
tests/test_upload/TestControllers.py

---
As per #436 , `isort` has released v5 which is a major version release with breaking changes. The PR addresses the same and updates the following:
- `.travis.yml`: `--rc` is deprecated and is on by default, file path needs to be provided explicitly.
- `README.md`: updated instructions on how to use `isort`
- In accordance with the new version, imports have been sorted in a bunch of files, the changes are minor and only concern the order.
Ref: https://pycqa.github.io/isort/docs/upgrade_guides/5.0.0/
NOTE: This base of the PR is #436 and it …

Migrate To `isort` v5

---

install/install.sh

**[FIX]**
---
Wrong syntax has been used in /install/install.sh file at [line 87](https://github.com/CCExtractor/sample-platform/blob/master/install/install.sh#L87), which leads to this error :
`./install.sh: line 87: read: Password for admin (will be created): : not a valid identifier
`
And similar error is spotted at lines [96](https://github.com/CCExtractor/sample-platform/blob/master/install/install.sh#L96), [100](https://github.com/CCExtractor/sample-platform/blob/master/install/install.sh#L100), thus not letting user to enter password at lines 96 ,100. This error has been fixed ( -s should be used before -p while using the options for read …

Fixed installation error

---

mod_regression/controllers.py
mod_regression/forms.py
mod_regression/models.py
mod_test/controllers.py
run.py
templates/regression/output_add.html
templates/regression/output_remove.html
templates/regression/test_view.html
templates/test/by_id.html
test-requirements.txt
tests/base.py
tests/test_regression/TestControllers.py

**[FEATURE]** 
---
fixes #447 
fixes #448 
fixes #449 
The following set of features were added :
1. Added multiple correct output feature, the platform can now detect multiple correct output files using RegressionTestOutputFiles table.
2. GUI to add and remove multiple correct outputs in regression test view.
3. Correct output can be chosen from  got values (if they're not None) of last 10 Test Runs.
4. Pass/Fail mechanism has also been modified so that a test is passed when the output file is one of the multiple correct files.

Multiple correct output Feature 

---

.github/workflows/main.yml
README.md
migrations/env.py
tests/TestLogConfiguration.py
tests/test_auth/TestControllers.py
tests/test_auth/__init__.py
tests/test_ci/__init__.py
tests/test_customized/__init__.py
tests/test_deploy/__init__.py
tests/test_home/__init__.py
tests/test_regression/__init__.py
tests/test_sample/__init__.py
tests/test_test/__init__.py
tests/test_upload/__init__.py

---
This changes the instructions in the README and the CI mypy test to run mypy over the entire repo (`mypy .`) instead of the mod_* directories (`mypy mod_*`).
Only running mypy over the mod_* directories causes mypy to not type check any of the python files in the root of the repo (You can confirm this by running `mypy mod_* --follow-imports=error` and seeing all of the imports that mypy ignores).  Using `mypy mod_*` also prevents mypy from type checking any of the tests. 
I also fixed/ignored some type errors that mypy found in code that …

[IMPROVEMENT] Use mypy on the entire repo

---

mod_auth/controllers.py
tests/test_auth/TestControllers.py

---
This contains a few fixes for some tests for `complete_signup` in mod_auth. Those fixes are:
- Fixing a race condition that caused the tests to fail if any of these tests ran more than 1 second after the set up code. More details about the bug can be found at https://github.com/CCExtractor/sample-platform/pull/540#issuecomment-837928237 (fixed in a51ebfecacf0eb3ee966d1c490d708734866bba1)
- Changing `test_if_link_expired` to actually test what would happen when using an expired link. Originally, it was testing what happened when sending an …

[FIX] Fix tests for complete_signup

---

mod_ci/controllers.py
mod_ci/models.py
tests/test_ci/TestControllers.py

---
Fixes (part of) #535 (see below for more info)
This fixes a bug in the generation of the PR comment that caused it to mark regression tests as failing if they produced one of the allowed variants of the expected output file, instead of correctly marking these tests as passing. I also added a few tests for this bug.
I don't think this is a complete fix for #535 because I don't think it completely accounts for the difference between https://github.com/CCExtractor/ccextractor/pull/1329#issuecomment-827744099 and …

[FIX] Fix incorrect PR comment generation

---

mod_ci/controllers.py
tests/test_ci/TestControllers.py

---
The PR aims to fix the typo causing the following error when deploying the CI status badges to Github.
```
Traceback (most recent call last):
File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File …
```

[quickfix] patch typo `test.platform.values` to `test.platform.value`

---

mod_auth/controllers.py

---
The `github_token_validity` function uses an outdated/invalid endpoint as seen [here](https://docs.github.com/en/rest/reference/apps#check-a-token).

[FIX] github_token_validity endpoint bugfix

---

mod_deploy/controllers.py
tests/base.py
tests/test_deploy/TestControllers.py

---
As referenced [here](https://github.blog/changelog/2021-04-19-sunsetting-api-authentication-via-query-parameters-and-the-oauth-applications-api/), the method previously used to authenticate was deprecated in May 2019

[FIX] Bugfix

---

.github/workflows/main.yml
mod_ci/controllers.py
tests/test_ci/TestControllers.py

---
**Prevent Running Tests on Platform Before Build Succeed**
This pull request involve making changes in the `mod_ci` module to re-configure the testing process, so that Tests won't start before the CCExtractor builds have been completed.
The following are the test details for various cases of triggering of platform:
- Push:
1. With GitHub Actions Failing(Both Builds Triggered) https://github.com/Tarun-Arora/ccextractor/commit/acfad7b96ee59ffbc11ce2a1df106453c7de1503
2. With GitHub Actions Succeeding(Both Builds Triggered): …

[IMPROVEMENT] Prevent Running Tests on Platform Before Build Succeed on Both OS

---

mod_ci/controllers.py
tests/test_ci/TestControllers.py

---
This PR ensures that tests are triggered on only that OS whose build is triggered, i.e if code related to only one OS is changed, now tests of other OS would not run.
Tests:
1. If only Windows build is triggered - https://github.com/Tarun-Arora/ccextractor/commit/9f15b8ffd836706fbe14a868f5d6d91b60348254
2. If only Linux build is triggered - https://github.com/Tarun-Arora/ccextractor/commit/6242137ba70bfb55c63631e3e0900ff4f05e633e
3. If both builds are triggered - https://github.com/Tarun-Arora/ccextractor/commit/9b8b74b85f7a4a5927e4ee63c98ed7643 …

[IMPROVEMENT] Run Tests Only on those platforms whose Build is triggered

---

install/ci-vm/ci-linux/ci/runCI
install/ci-vm/ci-windows/ci/runCI.bat
mod_ci/controllers.py
tests/test_auth/TestControllers.py
tests/test_ci/TestControllers.py

---
Currently we used to rebuild the CCExtractor from source during CI [ref](https://github.com/CCExtractor/sample-platform/blob/2dc41fd8dc371a28f4af0db856c4221324163fd8/install/ci-vm/ci-linux/ci/runCI#L77).
However, we can now reuse the artifacts generated during builds of CCExtractor from GitHub Action workflows, as per the [documentation](https://docs.github.com/en/rest/actions/artifacts#download-an-artifact). This PR implements the same.
FUTURE IMPROVEMENTS
Also we need to notice that documentation says that the redirect URL expires after 1 minute. Although since our artifact sizes are within ~15 MB currently, downloads are getting successful …

[IMPROVEMENT] Reuse CCExtractor builds from GitHub Actions for CI

---

mod_ci/controllers.py

---
This PR attempts to fix the unauthorized error(401) received while downloading the artifacts (due to a misconfiguration in config file from my side in #677).

[FIX] Fix failing download of GitHub Artifacts

---

install/ci-vm/ci-linux/startup-script.sh
install/installation.md
mod_upload/controllers.py
mod_upload/models.py

---
This pull request configures pure-FTPd to serve the upload of large samples directly to the GCS bucket without usage of platform server storage as an intermediatory.
Though most of the FTP configuration remains the same, broadly the following changes have been made:
- Change default directory of ftpd to `/repository/ftpd` instead of `/home`
- Allow `ftpuser` write access to GCS bucket
- GCP Firewall configuration changes to allow FTP communication through TCP port 21 and passive ports.

[FIX] Modify pure-FTP configuration for upload to GCS bucket directly

---

.gitignore
install/install.sh
install/nginx.conf
mod_auth/controllers.py
templates/test/by_id.html

---
This PR implements the following:
1. Download Log File button was visible during test runs, but the log file is received from KVMs/GCP instances after test completion only. Hence now that button would be hidden for that time period.
2. Nginx proxy_set_header is not required after the removal of X-Accel-Redirect
3. Invalid GitHub token was being logged after successful validation, hence changed that.
4. `temp` directory is created and used to store samples during nosetests, hence that directory is added to `.gitignore`

[IMPROVEMENT] Show download log file button after test completion, nginx & log message improvements

---

install/ci-vm/ci-windows/ci/runCI.bat
install/ci-vm/ci-windows/startup-script.ps1
mod_ci/controllers.py

---
This PR identifies the following error that occurred during Test Runs, specifically on the windows platform, due to rclone mounts...
FIX: On the Windows platform, we can copy the TestResults folder before tests start; since the size of the folder is small (216 MB at present), it would be feasible.

[FIX] Fix Windows tests I/O error due to TestResults file mounts

---

mod_ci/controllers.py
tests/test_ci/test_controllers.py

---
A simple two line change that also checks whether the pull request under question is not a draft request.

[IMPROVEMENT] Do not run the CI if it's a draft pull request

---

mod_ci/controllers.py
tests/test_ci/test_controllers.py

---
This PR is to fix the test status not being updated on the platform and on GitHub and showed "running" in case tests took time longer than the max timeout and the VM instance is deleted as well.

[FIX] Update test status, and post to GH, if instance force deleted

---

mod_ci/controllers.py

---
This is a follow up PR for #810 where the default of target_url in `update_status_on_github` was incorrectly set.

[FIX][URGENT] Fix target_url default in update_status_on_github

---

mod_ci/controllers.py

---
Hi @canihavesomecoffee @thealphadollar
Here's how I solved the current issue, please have a look at the queries
PREVIOUS QUERY
```
SELECT 
DISTINCT test_result.regression_test_id 
FROM 
regression_test_output_files, 
regression_test_output, 
test_result 
LEFT OUTER JOIN test_result_file ON test_result.test_id = test_result_file.test_id 
WHERE 
test_result.test_id = 4526 
AND test_result.expected_rc = test_result.exit_code 
AND (
test_result.exit_code != 0 
OR test_result.exit_code = 0 
AND test_result.regression_test_id = …
```

[FIX] Split regression_testid_passed query to optimize

---

mod_customized/controllers.py
tests/test_customized/test_controllers.py

---
This PR is to fix `/custom` endpoint which is currently down on [sampleplatform.ccextractor.org/custom](https://sampleplatform.ccextractor.org/custom/)
Background: This bug would be introduced by this #774

[FIX][URGENT] Fix /custom endpoint

---

config_sample.py
install/install.sh
mod_ci/controllers.py
run.py
tests/base.py
tests/test_ci/test_controllers.py

---
This PR is to delete old bot comments and repost the latest one, this helps to always keep the bot comments at the bottom of the PR
Also I noticed that `GITHUB_BOT` was not present in the production config as well as there is no way to initialize it in the `install.sh`, then I noticed that user not longer need to set it manually as PyGithub allows to fetch the name from the ci key itself, therefore removed the role of GITHUB_BOT.

[IMPROVEMENT] Delete and repost bot comment, remove GITHUB_BOT from config

---

.gitignore

---
This is to fix build svgs not present in the static folder because they were not in `.gitignore` and the CI/CD script had `git restore .` that delete those files...

[FIX] Fix CCX build svgs not present in static folder

---

mod_ci/controllers.py
tests/test_ci/test_controllers.py

---
This PR is to fix errors when there are both linux and windows tests and we get a SSL error due to the multiprocessing module
Error:

[FIX] Remove multiprocessing module usage to start tests, linearize tests' start

---

mod_ci/controllers.py
tests/test_ci/test_controllers.py
tests/test_sample/test_controllers.py

---
Closes #865 and this reverts the way draft PRs are being handled introduced in #775

[IMPROVEMENT] Fix working of draft PRs

---

mod_ci/controllers.py
tests/test_ci/test_controllers.py

---
This PR is a fix to #869, also check the platform name while fetching the last completed master test.

[FIX][URGENT] Check for platform while fetching last test on master

---

install/ci-vm/ci-windows/startup-script.ps1

---
Currently rclone mounts with full permission on windows. this PR restricts it to read-only.

[FIX] mount with read-only in rclone

---

mod_ci/controllers.py
tests/test_ci/test_controllers.py

fix: fix cron

---

install/ci-vm/installation.md
install/installation.md
install/sample_db.py
mod_ci/controllers.py
mod_test/controllers.py

---
This PR addresses several bugs encountered during the initial setup of the platform on a fresh VPS. The deployment process was _less than pleasant_, and this fix aims to improve the experience by fixing a few of the errors and improving the documentation to add a few missing pieces (like the necessity of `ccextractortester` and webhooks).
- The `sample_db.py` file was missing a few imports which were required for the creation of tables by SQLAlchemy. see [docs](https://flask-sqlalchemy.readthedocs.io/en/stable/models/#defining-models).
- The …

[Improvement] Fix first time install errors and update docs

---

database.py
mod_ci/controllers.py

---
Should fix the following warnings:
```
var/www/sample-platform/mod_ci/controllers.py:220: SAWarning: TypeDecorator DeclEnumType('linux', 'windows') will not produce a cache key because the cache_ok attribute is not set to True. This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions. Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf) …
```

fix: SQLAlchemy subquery and cache warnings

---

install/ci-vm/ci-windows/startup-script.ps1

---
While debugging the windows tests i noticed that a fair amount of time was spent copying the files from the mounted `TestResultsRemote` directory to the actually utilized `TestResults` directory. 
Replacing the mount + file copy operation with an `rclone copy` step reduced the VM startup time by around 10 mins since the latter is optimized for bulk file transfers.
The windows defender exclusion is necessary because windows was flagging rclone as a trojan while copying files for some reason, see …

perf: optimize startup time by using rclone copy directly

---

install/ci-vm/ci-linux/ci/runCI
install/ci-vm/ci-windows/ci/runCI.bat
install/ci-vm/ci-windows/startup-script.ps1

---
The windows tests have been getting stuck and timing out recently. The root cause was with how Rclone handled chunked reads for large files, this PR fixes this issue by passing an option to the underlying FUSE emulator that Rclone uses to modify how chunked reads are handled. For more information on this, refer [here](https://forum.rclone.org/t/vfs-is-slow-when-reading-in-small-8-bytes-chunks/40161).
The timeout has also been reduced to 10 minutes, the reasoning for this is that on previous successful windows tests (such as this …

fix: windows tests getting stuck and timing out

---

mod_ci/controllers.py

---
`last_passed_ on` is an integer field with a FK constraint on it whereas `last_test_master` is an instance of `Test`, to properly compare them we need to use the id of Test. 
This has been causing all test failures to be grouped under common test failures with master.

fix: test comparison

---

install/ci-vm/ci-linux/startup-script.sh

---
CCExtractor depends on the Noto Font family to be installed to run when `--out=spupng` is specified, see [here](https://github.com/hrideshmg/ccextractor/blob/d949d8fda94f65c706551e163115ad3ff151153f/src/lib_ccx/params.c#L35-L36). This font family is the default on Ubuntu, but for some reason it is not packaged by default with a GCP Ubuntu 24.04 Linux instance, causing regression id 162 to fail. 
This PR adds the missing font, should fix the regression.

fix: add missing font

---

install/ci-vm/ci-windows/startup-script.ps1

---
Similar to #938 but for Windows. Few tests were also failing because the windows VM did not have tesseract installed.

Rclone optimizations + tesseract fixes
